# Site settings
title: collab
email:
author: collab
description: "Collaborative Robotics Lab"
baseurl: ""
url: "https://collab.me.vt.edu/"
date_format: "%b %-d, %Y"
header_pages:
 - people.html
 - publications.html
 - talks.html
 - blog.html

show_social_icons: false
email:
github_username: VT-Collab
twitter_username:
linkedin_username:
youtube_id: UCVUHS9JE0tSakziQFkThhVQ

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

