# Site settings
title: collab
email:
author: collab
description: "Collaborative Robotics Lab at Virginia Tech. We create learning and control algorithms for robots that collaborate with people."
baseurl: ""
url: "https://collab.me.vt.edu/"
date_format: "%b %-d, %Y"
header_pages:
 - people.html
 - research.html
 - publications.html
 - videos.html
 - values.html

show_social_icons: true
email:
github_username:
twitter_username:
linkedin_username:
youtube_id: UCVUHS9JE0tSakziQFkThhVQ
photos: photos
wemet: wemet

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
