# Site settings
title: collab
email:
author: collab
description: "Collaborative Robotics Lab"
baseurl: ""
url: "http://collab.me.vt.edu/"
date_format: "%b %-d, %Y"
header_pages:
 - people.html
 - publications.html
 - talks.html
 - blog.html

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
