# Site settings
title: collab
email:
author: collab
description: "Collaborative Robotics Lab"
baseurl: ""
url: "https://collab.me.vt.edu/"
date_format: "%b %-d, %Y"
header_pages:
 - people.html
 - research.html
 - publications.html
 - talks.html
 - blog.html
 - wemet.html

show_social_icons: true
email:
github_username:
twitter_username:
linkedin_username:
youtube_id: UCVUHS9JE0tSakziQFkThhVQ
photos: photos

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
