# Site settings
title: Collab
email:
author: Collab
description: "Lab website in progress"
baseurl: ""
url: ""
date_format: "%b %-d, %Y"
header_pages:
 - publications.html

# Build settings
markdown: kramdown
permalink: pretty
paginate_path: blog/page:num
paginate: 4
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
